language: generic

services:
  - postgresql
  - docker

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


script:
  - psql -U postgres -d travis_ci_test -q -a -f ./chado/schemas/1.31/default_schema.sql > log.txt
  - sleep 30
  - docker run --rm --name flyway -v "$(pwd)/migrations":/flyway/sql boxfuse/flyway -url=jdbc:postgresql://127.0.0.1:5432/travis_ci_test -user=postgres -password=postgres migrate
