language: java

services:
  - postgresql

script:
  - psql -U postgres -d postgres -q -a -f ./chado/schemas/1.31/default_schema.sql > log.txt
  - export HOST_IP_ADDRESS="$(/sbin/ip route|awk '/default/ { print $3 }')"
  - gradle build
  - gradle flywayMigrate
